version: '3.8'

services:
  mysql:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_data
    volumes:
      - mysql_data:/var/lib/mysql 
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql 
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=user_data
    ports:
      - "3000:3000"

volumes:
  mysql_data:
